# remap prefix to ctrl-a
set-option -g prefix C-a
unbind C-b

# avoid auto renames
set allow-rename off

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
unbind r
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# set vi mode
set-window-option -g mode-keys vi

# set default terminal
set -g default-terminal "screen-256color"
